import { useCallback, useEffect, useState } from "react";
import { Button, DataTable, FormField, Input, Modal, Textarea, useToast } from "../../components/ui";
import { useAuth } from "../../context/AuthContext";
import { createAdminDestination, deleteAdminDestination, getAdminDestinations, updateAdminDestination } from "../../services/admin";
import { PageHeading, Pagination, TableToolbar } from "./AdminShared";
const blank = { name: "", country: "", description: "", imageUrl: "", highlights: "" };
export default function AdminDestinations() {
 const { token } = useAuth(); const toast = useToast(); const [items,setItems]=useState([]),[pagination,setPagination]=useState(),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[modal,setModal]=useState(null),[deleteTarget,setDeleteTarget]=useState(null),[form,setForm]=useState(blank),[saving,setSaving]=useState(false);
 const load=useCallback(async(page=1)=>{try{setLoading(true);const r=await getAdminDestinations({page,search},token);setItems(r.destinations);setPagination(r.pagination)}catch(e){toast.error(e.message)}finally{setLoading(false)}},[search,token,toast]); useEffect(()=>{const id=setTimeout(()=>load(),250);return()=>clearTimeout(id)},[load]);
 const change=(e)=>setForm({...form,[e.target.name]:e.target.value}); const open=(item)=>{setForm(item?{...item,highlights:(item.highlights||[]).join("\n")}:blank);setModal(item||"new")};
 async function save(e){e.preventDefault();if(!form.name||!form.country||!form.description||!form.imageUrl){toast.error("Name, country, description, and image are required.");return}try{setSaving(true);const body={...form,highlights:form.highlights.split("\n").map(x=>x.trim()).filter(Boolean)};if(modal?._id)await updateAdminDestination(modal._id,body,token);else await createAdminDestination(body,token);toast.success("Destination saved.");setModal(null);load(pagination?.page)}catch(err){toast.error(err.message)}finally{setSaving(false)}}
 async function remove(){try{setSaving(true);await deleteAdminDestination(deleteTarget._id,token);toast.success("Destination deleted.");setDeleteTarget(null);load(pagination?.page)}catch(err){toast.error(err.message)}finally{setSaving(false)}}
 return <section className="admin-page"><PageHeading title="Destinations" description="Curate the places travelers discover." action={<Button onClick={()=>open(null)}>New destination</Button>}/><TableToolbar search={search} setSearch={setSearch}/><DataTable loading={loading} data={items} keyField="_id" onRowClick={open} columns={[{key:"name",title:"Destination",render:r=><strong>{r.name}</strong>},{key:"country",title:"Country"},{key:"highlights",title:"Highlights",render:r=>(r.highlights||[]).length},{key:"actions",title:"",render:r=><Button size="sm" variant="ghost" onClick={(e)=>{e.stopPropagation();open(r)}}>Edit</Button>}]}/><Pagination pagination={pagination} onChange={load}/><Modal isOpen={Boolean(modal)} onClose={()=>setModal(null)} title={modal?._id?"Edit destination":"New destination"} size="lg" footer={<><Button variant="secondary" onClick={()=>setModal(null)}>Cancel</Button><Button form="destination-form" type="submit" loading={saving}>Save destination</Button></>}><form id="destination-form" className="admin-form" onSubmit={save}><div className="admin-form__grid"><FormField label="Name" required><Input name="name" value={form.name} onChange={change}/></FormField><FormField label="Country" required><Input name="country" value={form.country} onChange={change}/></FormField></div><FormField label="Description" required><Textarea name="description" value={form.description} onChange={change}/></FormField><FormField label="Image URL" required><Input name="imageUrl" type="url" value={form.imageUrl} onChange={change}/></FormField><FormField label="Highlights" helperText="One highlight per line"><Textarea name="highlights" value={form.highlights} onChange={change}/></FormField>{modal?._id&&<Button type="button" variant="danger" onClick={()=>{setDeleteTarget(modal);setModal(null)}}>Delete destination</Button>}</form></Modal><Modal isOpen={Boolean(deleteTarget)} onClose={()=>setDeleteTarget(null)} title="Delete destination" description="This cannot be undone. Destinations with packages cannot be deleted." footer={<><Button variant="secondary" onClick={()=>setDeleteTarget(null)}>Keep destination</Button><Button variant="danger" loading={saving} onClick={remove}>Delete</Button></>} /></section>;
}
